# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Cloudflared
version: "1.0.0"
slug: cloudflared
description: Cloudflare Tunnel client (formerly Argo Tunnel)
url: "https://github.com/0x1026/home-assistant_addons/tree/main/cloudflared"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_network: true
options:
  tunnel_token: ""
schema:
  tunnel_token: "str"
image: "ghcr.io/0x1026/{arch}-addon-cloudflared"
